name: API Performance Benchmark

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Target API URL to benchmark'
        required: true
        default: 'http://localhost:8000'
      requests:
        description: 'Number of requests to perform'
        required: true
        default: '1000'
      concurrency:
        description: 'Number of concurrent requests'
        required: true
        default: '10'
      technique:
        description: 'Optimization technique to test'
        required: true
        default: 'basic'
        type: choice
        options:
          - basic
          - caching
          - compression
          - batching
          - all

jobs:
  benchmark:
    name: Run API Benchmark
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f benchmarks/requirements.txt ]; then
            pip install -r benchmarks/requirements.txt
          else
            pip install pytest pytest-benchmark requests pandas matplotlib
          fi
      
      - name: Run benchmark script
        run: |
          cd benchmarks
          python benchmark.py --url ${{ github.event.inputs.target_url }} --requests ${{ github.event.inputs.requests }} --concurrency ${{ github.event.inputs.concurrency }} --technique ${{ github.event.inputs.technique }}
      
      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: |
            benchmarks/results/*.json
            benchmarks/results/*.csv
            benchmarks/results/*.png
          retention-days: 90