name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

jobs:
  validate:
    name: PR Validation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8==6.0.0
      
      - name: Basic lint check
        run: |
          # Only check for critical errors (syntax errors, undefined names)
          flake8 api/ benchmarks/ --count --select=E9,F63,F7,F82 --show-source --statistics
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Start services and run benchmarks
        run: |
          # Build and start all services with Docker Compose
          docker compose build
          docker compose up -d
          
          # Wait for services to be healthy
          echo "Waiting for services to be healthy..."
          timeout 60 bash -c 'while ! docker compose ps | grep -q "healthy"; do sleep 2; done'
          
          # Run benchmarks using the benchmarks service
          docker compose run --rm benchmarks python run.py --iterations 5 --concurrency 10 